@echo off
echo Pushing to original repository...
git push origin main
echo Syncing with forked repository...
git pull fork main --no-edit
echo Pushing to forked repository...
git push fork main
echo Done!
pause